apiVersion: v1
kind: Pod
metadata:
  labels:
    run: messages
  name: messages
spec:
  containers:
    - image: messages:0.0.1-SNAPSHOT
      name: messages
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: 8080
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: 8080
